news_websites = [
    {
        "_id" : 1,
        "url" : "https://timesofindia.indiatimes.com/news",
        "source_url" : "https://timesofindia.indiatimes.com",
        "topic" : "Latest News",
        "source" : "Times of India",
        "language": "english",
        "country": "India",
        "country_iso2_code":"IN",
        "country_iso3_code":"IND",
        "page_xpath" : "/html/body/div[1]/div[10]/div/div[2]/div[1]/ul[2]/li/a//@href",
        "news_xpath" : "//*[@class='main-content']/div/ul/li/span/a/@href",
        "articles_xpath" : "//*[@id='content']/div/div[2]",
        "title_xpath" : "//*[@class='_1Y-96']//text()",
        "description_xpath" : "//*[@class='_3YYSt clearfix  ']/text()",
        "image_xpath" : ["//*[@decoding='async']"]
    },
    {
        "_id" : 2,
        "url" : "https://www.hindustantimes.com/entertainment",
        "source_url" : "https://www.hindustantimes.com",
        "topic" : "Entertainment",
        "source" : "Hindustan Times",
        "language": "english",
        "country": "India",
        "country_iso2_code":"IN",
        "country_iso3_code":"IND",
        "page_xpath" : "//*[@class='listPagination']/ul/li/a/@href",
        "news_xpath" : "//*[@class='hdg3']/a/@href",
        "title_xpath" : ["//*[@class='hdg3']/text()","//*[@class='hdg1']/text()"],
        "description_xpath" : "//*[@class='storyDetails']/div[1]/p/text()",
        "image_xpath" : ["//*[@class='fullStory tfStory']/figure/span/img","//*[@class='cartHolder page-view-candidate fullStory']/figure/span/img","//*[@class='cartHolder page-view-candidate large fullStory']/figure/span/img"],

    },
    {
        "_id" : 3,
        "url" : "https://www.hindustantimes.com/latest-news",
        "source_url" : "https://www.hindustantimes.com",
        "topic" : "Latest News",
        "source" : "Hindustan Times",
        "language": "english",
        "country": "India",
        "country_iso2_code":"IN",
        "country_iso3_code":"IND",
        "page_xpath" : "//*[@class='listPagination']/ul/li/a/@href",
        "news_xpath" : "//*[@class='hdg3']/a/@href",
        "title_xpath" : ["//*[@class='hdg3']/text()","//*[@class='hdg1']/text()"],
        "description_xpath" : "//*[@class='storyDetails']/div[1]/p/text()",
        "image_xpath" : ["//*[@class='fullStory tfStory']/figure/span/img","//*[@class='cartHolder page-view-candidate fullStory']/figure/span/img","//*[@class='cartHolder page-view-candidate large fullStory']/figure/span/img"],
    },
    {
        "_id" : 4,
        "url" : "https://www.hindustantimes.com/business",
        "source_url" : "https://www.hindustantimes.com",
        "topic" : "Business",
        "source" : "Hindustan Times",
        "language": "english",
        "country": "India",
        "country_iso2_code":"IN",
        "country_iso3_code":"IND",
        "page_xpath" : "//*[@class='listPagination']/ul/li/a/@href",
        "news_xpath" : "//*[@class='hdg3']/a/@href",
        "title_xpath" : ["//*[@class='hdg3']/text()","//*[@class='hdg1']/text()"],
        "description_xpath" : "//*[@class='storyDetails']/div[1]/p/text()",
        "image_xpath" : ["//*[@class='fullStory tfStory']/figure/span/img","//*[@class='cartHolder page-view-candidate fullStory']/figure/span/img","//*[@class='cartHolder page-view-candidate large fullStory']/figure/span/img"],
    },
    {
        "_id" : 5,
        "url" : "https://www.hindustantimes.com/lifestyle/health",
        "source_url" : "https://www.hindustantimes.com",
        "topic" : "Health",
        "source" : "Hindustan Times",
        "language": "english",
        "country": "India",
        "country_iso2_code":"IN",
        "country_iso3_code":"IND",
        "page_xpath" : "//*[@class='listPagination']/ul/li/a/@href",
        "news_xpath" : "//*[@class='hdg3']/a/@href",
        "title_xpath" : ["//*[@class='hdg3']/text()","//*[@class='hdg1']/text()"],
        "description_xpath" : "//*[@class='storyDetails']/div[1]/p/text()",
        "image_xpath" : ["//*[@class='fullStory tfStory']/figure/span/img","//*[@class='cartHolder page-view-candidate fullStory']/figure/span/img","//*[@class='cartHolder page-view-candidate large fullStory']/figure/span/img"],
    },
    {
        "_id" : 6,
        "url" : "https://www.hindustantimes.com/science",
        "source_url" : "https://www.hindustantimes.com",
        "topic" : "Science",
        "source" : "Hindustan Times",
        "language": "english",
        "country": "India",
        "country_iso2_code":"IN",
        "country_iso3_code":"IND",
        "page_xpath" : "//*[@class='listPagination']/ul/li/a/@href",
        "news_xpath" : "//*[@class='hdg3']/a/@href",
        "title_xpath" : ["//*[@class='hdg3']/text()","//*[@class='hdg1']/text()"],
        "description_xpath" : "//*[@class='storyDetails']/div[1]/p/text()",
        "image_xpath" : ["//*[@class='fullStory tfStory']/figure/span/img","//*[@class='cartHolder page-view-candidate fullStory']/figure/span/img","//*[@class='cartHolder page-view-candidate large fullStory']/figure/span/img"],
    },
    {
        "_id" : 7,
        "url" : "https://www.hindustantimes.com/education",
        "source_url" : "https://www.hindustantimes.com",
        "topic" : "Education",
        "source" : "Hindustan Times",
        "language": "english",
        "country": "India",
        "country_iso2_code":"IN",
        "country_iso3_code":"IND",
        "page_xpath" : "//*[@class='listPagination']/ul/li/a/@href",
        "news_xpath" : "//*[@class='hdg3']/a/@href",
        "title_xpath" : ["//*[@class='hdg3']/text()","//*[@class='hdg1']/text()"],
        "description_xpath" : "//*[@class='storyDetails']/div[1]/p/text()",
        "image_xpath" : ["//*[@class='fullStory tfStory']/figure/span/img","//*[@class='cartHolder page-view-candidate fullStory']/figure/span/img","//*[@class='cartHolder page-view-candidate large fullStory']/figure/span/img"],
    },
    {
        "_id" : 8,
        "url" : "https://www.hindustantimes.com/sports",
        "source_url" : "https://www.hindustantimes.com",
        "topic" : "Sports",
        "source" : "Hindustan Times",
        "language": "english",
        "country": "India",
        "country_iso2_code":"IN",
        "country_iso3_code":"IND",
        "page_xpath" : "//*[@class='listPagination']/ul/li/a/@href",
        "news_xpath" : "//*[@class='hdg3']/a/@href",
        "title_xpath" : ["//*[@class='hdg3']/text()","//*[@class='hdg1']/text()"],
        "description_xpath" : "//*[@class='storyDetails']/div[1]/p/text()",
        "image_xpath" : ["//*[@class='fullStory tfStory']/figure/span/img","//*[@class='cartHolder page-view-candidate fullStory']/figure/span/img","//*[@class='cartHolder page-view-candidate large fullStory']/figure/span/img"],
    }

]